---
- name: Install Docker
  hosts: docker_server
  become: yes

  tasks:
  - name: Update apt
    apt:
      update_cache: yes

  - name: Install prerequisites
    apt:
      name:
      - ca-certificates
      - curl
      - gnupg
      - apt-transport-https
      state: present

  - name: Add Docker GPG key
    ansible.builtin.shell: |
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
    args:
      creates: /etc/apt/keyrings/docker.asc

  - name: Add Docker repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable"
      state: present
      filename: docker

  - name: Install Docker Engine
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      state: present
      update_cache: yes

  - name: Enable and start Docker
    systemd:
      name: docker
      enabled: yes
      state: started

  # Add the target user to the docker group to run Docker without sudo
  - name: Add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes

  # Ensure the docker group permissions are applied immediately
  - name: Apply new group membership
    ansible.builtin.shell: newgrp docker
    args:
      warn: false
    ignore_errors: true
